
spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/ordering_db?currentSchema=customer&binaryTransfer=true&reWriteBatchedInserts=true
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    platform: postgres
    schema: classpath:db/migration/V1.0.0.001_create_customer_schema.sql
    data: classpath:db/startup/init-data.sql
    initialization-mode: always
  flyway:
    locations: classpath:db/migration

logging:
  level:
    org.flywaydb: DEBUG